// mobile/App.tsx
import { Text, View, Button, FlatList } from 'react-native'
import { useEffect, useState } from 'react'

interface Book {
  title: string
  author: string
  published_year: number
  average_rating: number | null
}

export default function App() {
  const [books, setBooks] = useState<Book[]>([])

  async function loadBooks() {
    try {
      const response = await fetch('http://127.0.0.1:8000/api/books')
      console.log('STATUS:', response.status)

      const text = await response.text()
      console.log('RAW RESPONSE:', text)

      const data = JSON.parse(text)
      setBooks(data)
    } catch (error) {
      console.log('ERROR:', error)
    }
  }


  useEffect(() => {
    loadBooks()
  }, [])

  return (
    <View style={{ padding: 22 }}>
      <Text style={{ fontSize: 24 }}>Libros</Text>

      <Button title="Refrescar" onPress={loadBooks} />

      <Text>Libros cargados: {books.length}</Text>

      {books.map((book) => (
        <Text key={book.title}>
          {book.title} - Rating: {book.average_rating}
        </Text>
      ))}
    </View>
  )
}

// fronted/src/App.vue
<template>
  <div>
    <h1>Libros</h1>

    <button @click="loadBooks">Refrescar</button>

    <ul>
      <li v-for="book in books" :key="book.title">
        {{ book.title }} - Rating promedio: {{ book.average_rating }}
      </li>
    </ul>

    <p v-if="error">{{ error }}</p>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import { fetchBooks } from './services/bookService'
import type { Book } from './types/Book'

export default defineComponent({
  data() {
    return {
      books: [] as Book[],
      error: null as string | null
    }
  },
  methods: {
    async loadBooks(): Promise<void> {
      try {
        this.books = await fetchBooks()
      } catch (e) {
        this.error = 'No se pudieron cargar los libros'
      }
    }
  },
  mounted() {
    this.loadBooks()
  }
})
</script>
